ANOUC/Controllers/AnnoucementController.cs
using System;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ANOUC.Data;

namespace ANOUC.Controllers
{
  public class AnnoucementController : Controller
  {
    private IANOUCDataManager _db;

    public AnnoucementController() { }

    public AnnoucementController(IANOUCDataManager dataManager)
    {
      _db = dataManager;
    }

    // GET: Annoucement
    public ActionResult Index()
    {
      return View(_db.GetAnnoucements());
    }

    // GET: Annoucement
    public ActionResult Partial()
    {
      return PartialView("Index", _db.GetAnnoucements());
    }

    // GET: Annoucement/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      Annoucement annoucement = _db.GetAnnoucement(id.Value);
      if (annoucement == null)
        return HttpNotFound();

      return View(annoucement);
    }

    // GET: Annoucement/Create
    public ActionResult Create()
    {
      ViewBag.UsersIds = new SelectList(_db.GetUsers(), "Id", "FullName");
      return View();
    }

    // POST: Annoucement/Create
    [HttpPost]
    public ActionResult Create(
      [Bind(Include="Id,Content,Title,AddedDate,UserId")]
      Annoucement newAnnoucement)
    {
      if (ModelState.IsValid)
      {
        if (_db.AddAnnoucement(newAnnoucement))
          return RedirectToAction("Index");
        else
          throw new Exception("Error while saving Annoucement: " + newAnnoucement);
      }

      ViewBag.UsersIds = new SelectList(_db.GetUsers(), "Id", "FullName");
      return View(newAnnoucement);
    }

    // GET: Annoucement/Edit/5
    public ActionResult Edit(int? id)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      Annoucement annoucement = _db.GetAnnoucement(id.Value);
      if (annoucement == null)
        return HttpNotFound();

      ViewBag.UsersIds = new SelectList(_db.GetUsers(), "Id", "FullName");
      return View(annoucement);
    }

    // POST: Annoucement/Edit/5
    [HttpPost]
    public ActionResult Edit(
      [Bind(Include="Id,Content,Title,AddedDate,UserId")]
      Annoucement editedAnnoucement)
    {
      if (ModelState.IsValid)
      {
        if (_db.SaveAnnoucementChanges(editedAnnoucement))
          return RedirectToAction("Index");
        else
          throw new Exception("Error while saving changes in Annoucement: " + editedAnnoucement);
      }

      ViewBag.UsersIds = new SelectList(_db.GetUsers(), "Id", "FullName");
      return View(editedAnnoucement);
    }

    // GET: Annoucement/Delete/5
    public ActionResult Delete(int? id, bool? error)
    {
      if (id == null)
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

      Annoucement annoucement = _db.GetAnnoucement(id.Value);
      if (annoucement == null)
        return HttpNotFound();

      if (error.HasValue && error.Value == true)
        ViewBag.Error = true;

      return View(annoucement);
    }

    // POST: Annoucement/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int? id)
    {
      try
      {
        if (id == null)
          return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

        Annoucement annoucement = _db.GetAnnoucement(id.Value);
        if (annoucement == null)
          return HttpNotFound();

        if (_db.RemoveAnnoucement(annoucement))
          return RedirectToAction("Index");
        else
          throw new Exception("Error while removing Annoucement: " + annoucement);
      }
      catch(Exception)
      {
        return RedirectToAction("Delete", new { id = id, error = true });
      }
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
        _db?.Dispose();
      base.Dispose(disposing);
    }
  }
}

ANOUC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ANOUC</title>
    <meta name="description" content="@ViewBag.Description" />
    <meta name="keywords" content="@ViewBag.KeyWords" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Annoucements", "Index", "Annoucement", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  <!-- <li>@Html.ActionLink("Annoucements", "Index", "Annoucement")</li> -->

                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Annoucements <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <li>@Html.ActionLink("Annoucements list", "Index", "Annoucement")</li>
                      @if (User.Identity.IsAuthenticated)
                      {
                        <li>@Html.ActionLink("Add Annoucement", "Create", "Annoucement")</li>
                      }
                      <li class="divider"></li>
                      <li>@Html.ActionLink("List as PartialView", "Partial", "Annoucement")</li>
                    </ul>
                  </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ANOUC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>